trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: "rapid-alz-bicep-SP"
  RunNumber: $(Build.BuildNumber)
  ManagementGroupId : "58f7c0d7-3191-43d3-a803-62d8805626de" # Tenant Root Group ID
  Location: "australiaeast"
  # SubTemplateParameterFile: "parameters/subscription/platform/management-sub.parameters.json"
  SubTemplateFile: "platform/management/subscription.bicep"
  # RGTemplateParameterFile: "parameters/resourceGroup/resourceGroup.parameters.json"
  RGTemplateFile: "platform/management/resourceGroup.bicep"

jobs:
- job: PlatformManagement
  steps:

  - task: AzureCLI@2
    displayName: Az CLI Deploy Subscription
    name: place_identity_sub
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)'
      azureSubscription: '$(ServiceConnectionName)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --name place-sub-$(RunNumber) \
        --location $(Location) \
        --management-group-id $(ManagementGroupId) \
        --template-file $(SubTemplateFile)

  - task: AzureCLI@2
    displayName: Az CLI Deploy Resource Group
    name: create_update_resource_group
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)'
      azureSubscription: '$(ServiceConnectionName)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az account set --subscription identity
        az deployment sub create \
        --name create-rg-$(RunNumber) \
        --location $(Location) \
        --template-file $(RGTemplateFile)