trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: ParametersFile
  displayName: Parameters File
  type: string
  default: management-sub.parameters.json

variables:
  ServiceConnectionName: "rapid-alz-bicep-SP"
  RunNumber: $(Build.BuildNumber)
  DeploymentName: "sub-vend-$(RunNumber)"
  ManagementGroupId : "58f7c0d7-3191-43d3-a803-62d8805626de" # Tenant Root Group ID
  # ManagementGroupId : "poc"
  Location: "australiaeast"
  TemplateParameterFile: "parameters/subscription/${{ parameters.ParametersFile }}"
  TemplateFile: "subscription.bicep"

jobs:
- job: SubscriptonVending
  steps:

  - task: AzureCLI@2
    displayName: Az CLI Deploy Subscription
    name: create_mgs
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)'
      azureSubscription: '$(ServiceConnectionName)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --name $(DeploymentName) \
        --location $(Location) \
        --management-group-id $(ManagementGroupId) \
        --no-wait \
        --template-file $(TemplateFile) \
        --parameters $(TemplateParameterFile)